### ISSUE TITLE
ecrecover implementation 

### ISSUE THREAD

**Issue by jbgh** [se3000/ruby-eth#15]
I'm trying to implement ecrecover to get the public key from a signed message: https://github.com/ethereum/wiki/wiki/JavaScript-API#web3ethsign

I know you mentioned implementing libsecp256k1 support here https://github.com/se3000/ruby-eth/issues/1

Looks like ecrecover isn't possible right now with your current implementation since the signature in your recover_compact method is not the same as the signature generated by web3.  Let me know if this is incorrect.  Great work on the gem btw.

**Comment by se3000** [comment]
Ecrecover is supported; you wouldn't be able to determine the transaction signer/sender if it wasn't.

The signature is different because OpenSSL generates it instead of libsecp. Specifically, OpenSSL uses a [nondeterministic K value](https://bitcoin.stackexchange.com/questions/36127/problems-with-deterministic-ecdsa-based-on-rfc6979-in-bitcoin). This doesn't make it invalid, just that each time you run the signing function you get a different output. It is still a recoverable signature.

**Comment by se3000** [comment]
You can see the signature being recovered in ruby [here](https://github.com/se3000/ruby-eth/blob/master/lib/eth/tx.rb#L74-L75).

Is there anything else you're looking for with this issue?

**Comment by jbgh** [comment]
I see I was trying to recover from a signature generated by libsecp which is why I was running into trouble.  Thanks for the clarification.

**Comment by TonyWald** [comment]
Just to clarify, it sounds like because go-ethereum and web3 use libsecp to generate signatures, it's not possible to use this gem (which uses openssl instead) to recover keys from a message signed on the front-end of a web application using web3?

jbgh, assuming this is accurate, did you find any alternative approaches to recovering keys generated by libsecp in ruby?

**Comment by se3000** [comment]
That is not accurate. You can still recover the public key, the k value has nothing to do with recoverability, just in how the signature is generated. You should be able to recover the signature. If you can post some examples, I can try to point you in the right direction.

**Comment by se3000** [comment]
@jbgh I may have misunderstood your comment last time. You should be able to recover a signature generated by libsecp. Right now the gem does not support generating signatures with libsecp, but it can recover signatures generated by libsecp. Similarly, libsecp can recover signatures generated by this gem.

**Comment by blahutka** [comment]
In rails I'm using
`yarn install  eth-sig-util 'ethereumjs-util`

`bundle install schmooze`

```ruby
require 'schmooze'

class BabelSchmoozer < Schmooze::Base
  dependencies ethUtil: 'ethereumjs-util'
  dependencies sigUtil: 'eth-sig-util'

  method :bufferToHex, 'ethUtil.bufferToHex'
  method :recoverPersonalSignature, 'sigUtil.recoverPersonalSignature'
end
```

```ruby
 it 'matches public address' do
    babel = BabelSchmoozer.new(__dir__)
    msgBufferHex = babel.bufferToHex('Hello')

    address = babel.recoverPersonalSignature({data: msgBufferHex, sig: signature})
    expect(address.downcase).to eq(auth_service.eth_address.downcase)
  end
```
