### ISSUE TITLE
two different gem names ? its gem 'eth' in readme.md and gem 'ethereum-tx' in rubygems is pointing to this repo.

### ISSUE THREAD

**Issue by 5hanth** [se3000/ruby-eth#28]

**Comment by se3000** [comment]
This gem was formerly called `ethereum-tx` and it followed the ruby naming convention of gem names to classes, making the actual class `Ethereum::Tx`. This ran into some namespace collisions around `Ethereum` with the already existing [ruby full node implementation](https://github.com/cryptape/ruby-ethereum). I renamed the gem because it wasn't worth it to try to coordinate.
