### ISSUE TITLE
Create Eth::Key from key file

### ISSUE THREAD

**Issue by marekkirejczyk** [se3000/ruby-eth#6]
It would be great to create Eth::Key from existing key, e.g.:

```ruby
Eth::Key.new file: path_to_key
```
and/or:
```ruby
Eth::Key.new json: private_key
```

**Comment by se3000** [comment]
Cool, looked into this a little bit. Just dropping a couple relevant links here for future reference:

The spec for encrypting:
https://github.com/ethereum/wiki/wiki/Web3-Secret-Storage-Definition

It looks like PBKDF2 is required, which [should be](https://ruby-doc.org/stdlib-2.0.0/libdoc/openssl/rdoc/OpenSSL/PKCS5.html) supported by OpenSSL. If that turns out not to work, I might put this in a separate gem to avoid extra dependencies.

**Comment by marekkirejczyk** [comment]
Awesome, I'l try to take a closer look next week and get back here.

**Comment by se3000** [comment]
Ok, added this in v0.4.3.

encrypt:
```ruby
json = Eth::Key.encrypt key, password
```

decrypt:
```ruby
key = Eth::Key.decrypt data, password
```
I left reading and writing to disk out of this, the gem expects and returns JSON for now. We can add support for file paths and more syntactic sugar later, for now the base functionality should be there. 

I tested compatibility with geth and myetherwallet. Feel free to reopen if I missed anything or you run into any bugs.
